name: Deploy to zingg.co

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 123.hosttech.eu
          username: chriz
          password: Git21Hub06!
          local-dir: ./
          server-dir: /zingg.co/httpdocs/
          exclude: |
            **/.git*
            **/.git*/**
            .github/**